language: python

dist: xenial

sudo: required

python:
  - '3.7'

install:
  - pip install tox-travis codecov

script:
  - test_data_dir=/tests/test_data/
  - echo {\"u1\":\"${USERNAME1}\",\"p1\":\"${PASSWORD1}\"} > $(pwd)${test_data_dir}secrets1.json
  - echo {\"u1\":\"${USERNAME1}\",\"p1\":\"${PASSWORD1}\",\"u2\":\"${USERNAME2}\",\"p2\":\"${PASSWORD2}\"} > $(pwd)${test_data_dir}secrets2.json
  - tox
  - codecov 
  - sleep 10  # Github build status would not be updated by "codecov" otherwise
