language: python

dist: xenial

sudo: required

python:
  - '3.7'

install:
  - pip install tox-travis codecov

script: 
  - tox
  - codecov 
  - sleep 10  # Github build status would not be updated by "codecov" otherwise
  